name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        
    - name: Test with pytest
      run: |
        python3 -m pytest -v tests/test_main.py